<body style=max-width:80ch;margin:auto>
<h1 class="entry-title" style="margin-bottom:15px;">Understanding a mysterious <code>RPC_<wbr/>E_<wbr/>WRONG­THREAD</code> exception when we’re on the right thread</h1>  <!-- .entry-meta -->

<p>Last time, we were looking a customer whose code tried to catch all exceptions, but <a href="/code/why-am-i-getting-an-unhandled-exception-from-my-c-function-that-catches-all-exceptions" title="Why am I getting an unhandled exception from my C++ function that catches all exceptions?"> accidentally raised an exception from the code that handled all exceptions</a>. (You had one job!)</p>
<p>The code in question looked like this:</p>
<pre>winrt::fire_and_forget MyClass::DoSomethingAsync()
{
    auto lifetime = get_strong();
    try {
        auto name = co_await m_user.GetNameAsync();
        m_label.Text(name);
    } catch (...) {
        m_label.Text(L"unknown");
    }
}
</pre>
<p>The obvious exception that this code was trying to catch was an exception from <code>Get­Name­Async</code>, and it handled it by just reporting the name as “unknown” if the name could not be obtained.</p>
<p>But the problem was that its recovery code threw an exception too!</p>
<p>In this particular case, the exception was <code>RPC_<wbr>E_<wbr>WRONG­THREAD</wbr></wbr></code>. The customer noted that the crash occurred if the user closed their XAML window while the <code>Get­Name­Async</code> was still running.</p>
<p>Okay, with that clue, it becomes possible to develop some theories as to what happened.</p>
<p>The <code>m_label</code> here is a XAML text block, and XAML objects have thread affinity. It’s apparent that the call starts on the correct thread, because in the cases where the user doesn’t close the XAML window, the code executes successfully without an exception.</p>
<p>The other case that you get a <code>RPC_<wbr/>E_<wbr/>WRONG­THREAD</code> exception from XAML is if you try to use XAML from a thread on which XAML is not initialized. And that fits the scenario here: The user closed the XAML window, so the app cleans up XAML for the thread that was hosting the window, and then the <code>Get­Name­Async</code> operation completes, and the code resumes executing on a thread that has had XAML uninitialized out from under it.</p>
<p>It then attempts to set the name into the <code>m_label</code> that fails with <code>RPC_<wbr/>E_<wbr/>WRONG­THREAD</code>: You can’t do XAML things on this thread any more.</p>
<p>The exception is caught, and the exception handler recovers by… trying to set the name into the <code>m_label</code> again! The anthropomorphized XAML runtime says, “C’mon, man, like I just told you to stop doing that,” and throws <code>RPC_<wbr/>E_<wbr/>WRONG­THREAD</code> a second time.</p>
<p>Another possible scenario is that the thread that hosted the XAML window not only shut down XAML on that thread, but in fact managed to exit entirely. The coroutine machinery in C++/WinRT follows the same policy as C# and PPL and resumes Windows Runtime operations on the same COM apartment on which they started. But in this case, the original apartment is gone. In that case, <a href="https://devblogs.microsoft.com/oldnewthing/20191128-00/?p=103157" title="How do you get into a context via IContextCallback::ContextCallback?"> the attempt to get back to the original context</a> fails with <code>RPC_<wbr/>E_<wbr/>DISCONNECTED</code>, because all of the references to the original apartment <a href="https://devblogs.microsoft.com/oldnewthing/20191126-00/?p=103140" title="Yo dawg, I hear you like COM apartments, so I put a COM apartment in your COM apartment so you can COM apartment while you COM apartment"> got disconnected as part of apartment rundown</a>. We looked at this problem <a href="https://devblogs.microsoft.com/oldnewthing/20230210-00/?p=107815" title=""> a little while ago</a>.</p>
<p>In this customer’s case, they can just abandon the label-setting work if the attempt to set the fallback label fails, and the solution from last time is appropriate: Add a second catch block to catch and ignore exceptions from the exception handler.</p>
<p><b>Bonus chatter</b>: From the crash stack, you can observe which of the two cases we are in:</p>
<pre>contoso!std::experimental::coroutine_handle&lt;void&gt;::operator()+0x5
contoso!winrt::impl::resume_apartment_callback+0x9
...
</pre>
<p>The coroutine was resumed from <code>resume_<wbr/>apartment_<wbr/>callback</code>, which is <a href="https://devblogs.microsoft.com/oldnewthing/20230124-00/?p=107746" title="Inside C++/WinRT: Apartment switching: The basic idea"> the function that C++/WinRT passes to <code>IContext­Callback::<wbr/>Context­Callback</code></a>. This means that we did successfully get back to the original apartment, and the problem was that the coroutine is trying to access XAML from a thread that has already uninitialized XAML.</p>
<p>If the problem was that C++/WinRT could not get back to the correct apartment, then the coroutine <a href="https://devblogs.microsoft.com/oldnewthing/20230131-00/?p=107770" title="Inside C++/WinRT: Apartment switching: Error reporting"> would have resumed from <code>resume_<wbr/>apartment_<wbr/>sync</code></a>.</p>
<p><b>Bonus bonus chatter</b>: In the case where C++/WinRT cannot get back to the correct apartment, it will throw the <code>RPC_<wbr/>E_<wbr/>DISCONNECTED</code> from whatever thread it happens to be on when it gets stuck. In that case, the exception handler may find itself running on the wrong apartment.</p>
<p>You can try to detect this case by checking what apartment you are running in, but one of the design principles of the Windows Runtime is that recoverable errors should not be reported via exceptions, but rather by reporting an error in some in-API manner, like a status code or a <code>Succeeded</code> property. If you are catching an exception, then something terrible has probably happened and you may just want to fail fast and stop before things get out of control.</p>
<p><b>Bonus bonus bonus chatter</b>: Some of the older Windows Runtime classes still use exceptions to report recoverable errors, but we are slowly updating them to provide non-exceptional versions, like <code>Http­Client.<wbr/>Try­Get­Async</code> as a non-exceptional alternative to <code>Http­Client.<wbr/>Get­Async</code>.</p>


</body>